Update documentation and port build system to CMake
andy-shev/iotools pull request #5
Opened 2024-10-24 15:29 UTC by aaron-sierra

These changes include:
* expanding the output of `iotools --help` and the project README.
* providing a cross-build compatible alternative to `iotools --make-links`.
*  porting the build system to CMake for future dependencies *and* more trivial integration into Buildroot's package build framework.

# Buildroot package reference files

## Config.in

```
config BR2_PACKAGE_IOTOOLS
        bool "iotools"
        help
          The iotools package provides a set of simple command line
          tools which allow access to hardware device registers.
          Supported register interfaces include PCI, IO, memory mapped
          IO, SMBus, CPUID, and MSR. Also included are some utilities
          which allow for simple arithmetic, logical, and other
          operations.

          https://github.com/aaron-sierra/iotools/

if BR2_PACKAGE_IOTOOLS

config BR2_PACKAGE_IOTOOLS_NOLINKS
        bool "Exclude symlinks"
        default n

endif
```

## iotools.mk

```
###############################################################################
#
# iotools
#
###############################################################################

IOTOOLS_VERSION = e589d289de5aa6328dcc706b88d0761582d5c5f1
IOTOOLS_SITE = $(call github,aaron-sierra,iotools,$(IOTOOLS_VERSION))
IOTOOLS_LICENSE = GPLv2
IOTOOLS_LICENSE_FILES = COPYING
IOTOOLS_CONF_OPTS = -DSTATIC=OFF

ifeq ($(BR2_PACKAGE_IOTOOLS_NOLINKS),y)
IOTOOLS_CONF_OPTS += -DINSTALL_LINKS=OFF
endif

$(eval $(cmake-package))
```

2024-10-31 17:20 UTC, andy-shev requested changes
Thanks for your hard work on this! It's almost good, some comments are spread around the commits.

2024-10-31 17:20 UTC, andy-shev commented on iotools.c
> +static const char *bin_name = NULL;
Hmm... What's wrong with the passing it as a parameter to the respective functions?
I believe `argv[0]` is used there to show the actual file that has been called (because of links they may be placed in different folders).

Also comment to all your patches, can you add a Signed-off-by to all of the commits, please?

2024-10-31 17:20 UTC, andy-shev commented on iotools.c
> +	bin_name = basename(argv[0]);
Is this portable? `man 3 basename` shows that there are two versions: POSIX and GNU. Which one is in use here? `libgpiod` project went eventually with local helper to be portable.

2024-10-31 17:20 UTC, andy-shev commented on Makefile
> -rinstall: $(BINARY)
Can you move the script from the commit message to a real (new) file?

2024-10-31 17:20 UTC, andy-shev commented on CMakeLists.txt
> +	VERSION 1.6
I believe it deserves to start a new major version, let's say `2.0`.

2024-10-31 17:20 UTC, andy-shev commented on Makefile
> -VER_MINOR = 6
Let's first fix this in upstream as prerequisite patch to the series (at least to this change). Are you okay to add such a patch or should I do? If you are going to do, choose `1.8` perhaps, or `1.7a`, I don't remember if we have any issues if we add a letter at the end of version. In any case this will effectively mean to split this PR to two.

2024-10-31 17:20 UTC, andy-shev commented on CMakeLists.txt
> +
Please, refer in the commit message to the function as `dlopen()` (note the parentheses).

2024-10-31 17:20 UTC, andy-shev commented on CMakeLists.txt
> +option(INSTALL_LINKS "Generate symlinks during install?" ON)
Does it mean the default is on? I would move it `OFF` in this case (yes I know that initially it was like this, but again, I don't think distros will like this to be the default and I believe many of them will want to simply turn it `OFF`).

2024-10-31 17:20 UTC, andy-shev commented on CMakeLists.txt
> +if (INSTALL_LINKS)
Cool, interesting trick!
The question here is how is it portable? And what if `readelf` is not available (may this be the case)?

2024-11-05 16:52 UTC, andy-shev approved these changes
I'm going to apply the first part for now and then we can review the second one, there are still unanswered questions as far as I can see.

2024-11-05 16:54 UTC, andy-shev commented
> I'm going to apply the first part for now and then we can review the second one, there are still unanswered questions as far as I can see.

Ah, I can't do this. Please, split this to two PRs.

2024-11-05 16:54 UTC, closed without merging

2024-11-11 20:07 UTC, aaron-sierra reviewed
These comments have been sitting "[Pending](https://github.com/orgs/community/discussions/10369)" in a review on my side, because I failed to submit them. Sorry for the delay.

2024-11-11 20:07 UTC, aaron-sierra commented on README.md
> +* `MAKE_LINKS` - If set to ON (or 1, etc.), command symlinks to the binary are
`MAKE_LINKS` is actually `INSTALL_LINKS` to avoid collision/confusion with the `make_links` function in the CMakeLists.

2024-11-11 20:07 UTC, aaron-sierra commented on README.md
> +* `MAKE_LINKS` - If set to ON (or 1, etc.), command symlinks to the binary are
Corrected in rebased 3e0166d9cc832544279f27688279d6060c81b4b0

2024-11-11 20:07 UTC, aaron-sierra commented on iotools.c
> +	bin_name = basename(argv[0]);
The GNU version is used here, because `_GNU_SOURCE` is defined for the build. It was originally defined to get access to `O_DIRECT` in da89515028774db4fab001e2e7c9f0b93e4623b0 circa 2008.

2024-11-11 20:07 UTC, aaron-sierra commented on CMakeLists.txt
> +if (INSTALL_LINKS)
The LLVM and binutils projects provide `readelf` implementations that are compatible with my proposal. Those are essential components of their respective build systems, so it should be safe to assume it will be available at build-time.

2024-11-11 20:07 UTC, aaron-sierra commented on CMakeLists.txt
> +option(INSTALL_LINKS "Generate symlinks during install?" ON)
Yes, that default preserves this project's original view of symlinks as the primary means to access internal commands, because this work is merely a port from pure **make** to **cmake**.

I understand that your position is for the benefit of the downstream packager, but now that the packager can easily choose their preference, is it really worth changing the project's default without more concrete evidence of a global preference? *If* you still want to change the default, that should be done as an explicit commit after the **cmake** port has landed.

2024-11-11 20:07 UTC, aaron-sierra commented on CMakeLists.txt
> +
Those three paragraphs are a direct quote from the [preceding URL](https://cmake.org/cmake/help/latest/policy/CMP0065.html), but no problem.

2024-11-11 20:07 UTC, aaron-sierra commented on iotools.c
> +static const char *bin_name = NULL;
> Also comment to all your patches, can you add a Signed-off-by to all of the commits, please?

Sure thing.

2024-11-11 20:07 UTC, aaron-sierra commented on Makefile
> -rinstall: $(BINARY)
Ha, sure. I almost did in my first draft.

2024-11-11 20:07 UTC, aaron-sierra commented on CMakeLists.txt
> +	VERSION 1.6
Sounds good to me.

2024-11-11 20:07 UTC, aaron-sierra commented on Makefile
> -VER_MINOR = 6
How about inserting the 1.8 version[^1] just before the **cmake** transition? The final history would be like this (in Git-order):

[^1]: https://cmake.org/cmake/help/v3.0/command/project.html

* (New) Bump version to 2.0
* build: Add cross-build compatible symlink install
* build: Adopt "new" policy for CMP0065
* build: Port build system to CMake
* build: Do not call --make-links during install
* (New) Bump version to 1.8
* README: Add Usage section
* README: Convert to Markdown format
* README: Fix long line in About section
* build: Drop rinstall make target
* Expand help output

2024-11-11 20:07 UTC, aaron-sierra commented on iotools.c
> +static const char *bin_name = NULL;
> I believe `argv[0]` is used there to show the actual file that has been called

Fair enough. I see that the subcommands use `argv[0]` directly, via `check_prereqs()`. I'll drop that commit.

2024-11-11 20:39 UTC, andy-shev commented
> These comments have been sitting "[Pending](https://github.com/orgs/community/discussions/10369)" in a review on my side, because I failed to submit them. Sorry for the delay.

Interestingly that I can't reply in place there. So here are my answers:
1) Even if `readelf` is provided by main toolchains, can we actually _test_ for it as we do for many other things in whatever buildsystem we have (CMake for this case)? Then we will be sure that it's present and we will know the exact path to it.
2) I got it, so, can we rather _first_ to change the default and _then_ update to CMake? I really don't like the tools like `xor` to be populated on the real filessystems, it's prone to collisions sooner or later. Same for any other names. If you want make this work, then it's probably should be installed in a separated folder (like Git does) and user can add it to the PATH to be able to use. At least this solution will be much more cleaner (and I would not prevent the links to be created as a part of the build process).

2024-11-14 02:38 UTC, aaron-sierra commented
I like the idea of shell completion as a future feature. I also think that reorganization of the link install location or other execution refactoring could reasonably occur in the future, too. At this time, I would like to preserve functionality that I (and former coworkers) have relied on for years.

1. My proposal relies on `CMAKE_READELF`, which is automatically discovered by CMake since 3.16.0 (2019) via Modules/CMakeFindBinUtils.cmake. That doesn't cover down to 3.0.0 (2014) like I'd intended, so I'm setting up version compatibility testing and have marked #7 as Draft. Do you have issues with that discovery mechanism, assuming it can be backported?
2. How about I drop the 2.0.0 version bump commit, you land the pull request (after I address number **1** above), you push a commit making the default change, then you push a commit setting the 2.0.0 version?

2024-11-20 17:30 UTC, andy-shev commented
> I like the idea of shell completion as a future feature. 

Yes, I'm not talking about fulfilling it right now.

> I also think that reorganization of the link install location or other execution refactoring could reasonably occur in the future, too. At this time, I would like to preserve functionality that I (and former coworkers) have relied on for years.

Okay.

>     1. My proposal relies on `CMAKE_READELF`, which is automatically discovered by CMake since 3.16.0 (2019) via Modules/CMakeFindBinUtils.cmake. That doesn't cover down to 3.0.0 (2014) like I'd intended, so I'm setting up version compatibility testing and have marked [Port build system to CMake (2/2 from #5) #7](https://github.com/andy-shev/iotools/pull/7) as Draft. Do you have issues with that discovery mechanism, assuming it can be backported?

2014 is 10 years ago. I think we may rely on the feature, but make sure we require minimum CMake version.

>     2. How about I drop the 2.0.0 version bump commit, you land the pull request (after I address number **1** above), you push a commit making the default change, then you push a commit setting the 2.0.0 version?

Sounds like a plan!